name: Update OISST catalogs

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 17 * * *"

jobs:
  update:
    name: Update OISST catalogs
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Provision with µMamba
      uses: mamba-org/provision-with-micromamba@v10

    - name: Install dev version of fsspec-reference-maker
      shell: bash -l {0}
      run: pip install git+https://github.com/lsterzinger/fsspec-reference-maker.git@5072d614cbb6cfa0f497dece422a953c7c4812ab

    - name: List packages
      shell: bash -l {0}
      run: |
        which python
        python -m pip list

    - name: Update OISST data
      shell: bash -l {0}
      run: python daily.py

    - name: Commit and push if changed
      run: |
        git config user.name "Auto OISST"
        git config user.email "actions@users.noreply.github.com"
        git add cache complete preliminary
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
